from flask import Flask, render_template, request, send_from_directory
import pandas as pd
import os
import zipfile
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors

app = Flask(__name__)

UPLOAD_FOLDER = "uploads"
REPORT_FOLDER = "report_cards"

os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(REPORT_FOLDER, exist_ok=True)


# ---------- GRADING LOGIC ----------
def subject_grade(marks):
    if marks >= 90:
        return "A+"
    elif marks >= 75:
        return "A"
    elif marks >= 60:
        return "B"
    elif marks >= 40:
        return "C"
    else:
        return "F"


# ---------- MAIN ROUTE ----------
@app.route("/", methods=["GET", "POST"])
def upload():
    if request.method == "POST":
        # Get form values
        college_name = request.form.get("college_name", "Unknown College")
        class_name = request.form.get("class_name", "Unknown Class")
        semester = request.form.get("semester", "Unknown Semester")
        academic_year = request.form.get("academic_year", "Unknown Year")

        # Check file
        file = request.files.get("file")
        if not file:
            return "No file uploaded", 400

        # Save Excel
        excel_path = os.path.join(UPLOAD_FOLDER, "marks.xlsx")
        file.save(excel_path)

        # Read Excel
        df = pd.read_excel(excel_path, engine="openpyxl")

        # Detect subjects dynamically
        fixed_columns = ["RollNo", "Name"]
        subjects = [col for col in df.columns if col not in fixed_columns]

        # Apply grades
        for subject in subjects:
            df[f"{subject}_Grade"] = df[subject].apply(subject_grade)

        # Total, percentage, result
        df["Total"] = df[subjects].sum(axis=1)
        df["Percentage"] = df["Total"] / len(subjects)
        df["Result"] = df.apply(
            lambda r: "FAIL" if any(r[sub] < 40 for sub in subjects) else "PASS",
            axis=1
        )

        generated_files = []

        # ---------- PDF GENERATION ----------
        for _, row in df.iterrows():
            filename = f"{row['RollNo']}_{row['Name']}.pdf"
            pdf_path = os.path.join(REPORT_FOLDER, filename)

            c = canvas.Canvas(pdf_path, pagesize=A4)
            width, height = A4
            margin_left = 50
            margin_top = height - 50

            # --- Header ---
            c.setFont("Helvetica-Bold", 20)
            c.drawCentredString(width / 2, margin_top, college_name)

            c.setFont("Helvetica-Bold", 14)
            c.drawCentredString(width / 2, margin_top - 25, f"{class_name} | {semester}")
            c.drawCentredString(width / 2, margin_top - 45, f"Academic Year: {academic_year}")

            c.setLineWidth(1.2)
            c.line(margin_left, margin_top - 55, width - margin_left, margin_top - 55)

            # --- Student Info ---
            c.setFont("Helvetica-Bold", 12)
            y_position = margin_top - 80
            c.drawString(margin_left, y_position, f"Name: {row['Name']}")
            c.drawString(width / 2 + 50, y_position, f"Roll No: {row['RollNo']}")

            # --- Subject Table ---
            table_data = [["Subject", "Marks", "Grade"]]
            for subject in subjects:
                table_data.append([subject, row[subject], row[f"{subject}_Grade"]])

            table = Table(table_data, colWidths=[250, 100, 100])
            table.setStyle(TableStyle([
                ("GRID", (0,0), (-1,-1), 1, colors.black),
                ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#d9d9d9")),
                ("TEXTCOLOR", (0,0), (-1,0), colors.black),
                ("ALIGN", (1,1), (-1,-1), "CENTER"),
                ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
                ("FONTNAME", (0,1), (-1,-1), "Helvetica"),
                ("FONTSIZE", (0,0), (-1,-1), 11),
                ("BOTTOMPADDING", (0,0), (-1,0), 8),
                ("TOPPADDING", (0,0), (-1,0), 8),
            ]))

            table_width, table_height = table.wrapOn(c, width, height)
            table.drawOn(c, margin_left, y_position - table_height - 20)

            # --- Summary ---
            summary_y = y_position - table_height - 50
            c.setFont("Helvetica-Bold", 12)
            c.drawString(margin_left, summary_y, f"Total Marks: {row['Total']}")
            c.drawString(margin_left, summary_y - 20, f"Percentage: {row['Percentage']:.2f}%")
            c.drawString(margin_left, summary_y - 40, f"Result: {row['Result']}")

            # --- Footer ---
            c.setFont("Helvetica-Oblique", 9)
            c.drawCentredString(width / 2, 20, "Generated by Vocal Care System")

            c.save()
            generated_files.append(filename)

        # ---------- ZIP CREATION ----------
        zip_name = "All_Report_Cards.zip"
        zip_path = os.path.join(REPORT_FOLDER, zip_name)
        with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for file in generated_files:
                zipf.write(os.path.join(REPORT_FOLDER, file), arcname=file)

        return render_template("success.html", files=generated_files, zip_file=zip_name)

    return render_template("upload.html")
    

# ---------- DOWNLOAD SINGLE PDF ----------
@app.route("/download/<filename>")
def download(filename):
    return send_from_directory(REPORT_FOLDER, filename, as_attachment=True)


# ---------- DOWNLOAD ALL (ZIP) ----------
@app.route("/download-all")
def download_all():
    return send_from_directory(REPORT_FOLDER, "All_Report_Cards.zip", as_attachment=True)


if __name__ == "__main__":
    app.run(debug=True)
